language: csharp
mono:
  - latest
  - 4.2.4
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      sudo: required
  allow_failures:
    - mono: latest
  fast_finish: true
before_install:
    - ./.travis/install.sh
script:
  - ./build.sh --target "Travis"
