language: csharp
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
    - os: linux
      dist: trusty
      mono: 4.2.4
    - os: osx
      mono: latest
  allow_failures:
    - mono: latest
  fast_finish: true

script:
  - ./build.sh --target "Travis"
