install:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $url = "http://download.microsoft.com/7/0/3/703455ee-a747-4cc8-bd3e-98a615c3aedb/dotNetFx35setup.exe"
  - ps: $wc.DownloadFile($url, 'dotNetFx35setup.exe')
  - ps: dotNetFx35setup.exe

build_script: 
  - msbuild nunit.sln /p:Configuration=Release /t:Rebuild
  - msbuild src\NUnitFramework\NUnitLiteCF35.sln /p:Configuration=Release /t:Rebuild
  
test_script:
  - msbuild NUnit.proj /t:TestAll /p:Configuration=Release /p:ResultFormat=nunit2 /p:ContinueOnFailure=ErrorAndContinue
#  - ps: $wc = New-Object 'System.Net.WebClient'
#  - ps: $dir = "bin\Release\Results"
#  - ps: $uri = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
#  - ps: foreach($item in (dir $dir "*.xml")) { $wc.UploadFile($uri, $item.FullName) }
  
