build_script: 
  msbuild nunit.sln /p:Configuration=Release /t:Rebuild
  
test_script:
  cmd: cd bin\Release
  cmd: nunit-console.exe nunit.agent.tests.dll
  cmd: nunit-console.exe nunit-console.tests.dll
