build_script: 
  msbuild nunit.sln /p:Configuration=Release /t:Rebuild
  
test_script:
  - build /t:TestAll /p:Configuration=Release /p:ResultFormat=nunit2
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $dir = "bin\Release\Results"
  - ps: $uri = "https://ci.appveyor.com/api/testresuls/nunit/$($env:APPVEYOR_JOB_ID)"
  - ps: foreach($item in (dir $dir "*.xml") { $wc.UploadFile($uri, $item.FullName) }
  
